# yaml-language-server: $schema=https://github.com/springernature/halfpipe/releases/latest/download/schema.json
team: <team name>
pipeline: halfpipe-.e2e-init
platform: concourse
feature_toggles:
- update-pipeline
triggers:
- type: git
  watched_paths:
  - .e2e/init
tasks:
- type: run
  name: <task name>
  script: <script>
  docker:
    image: <image:tag>
