team: halfpipe-team
pipeline: halfpipe-e2e-docker-push-with-docker-trigger

triggers:
- type: docker
  image: springernature/alpine:tag
- type: pipeline
  pipeline: halfpipe-example-docker-push
  job: docker-push
- type: git
  branch: main
  watched_paths:
  - .e2e/docker-push-with-docker-trigger

tasks:
- type: docker-push
  name: push to docker registry
  username: rob
  password: verysecret
  image: eu.gcr.io/halfpipe-io/halfpipe-team/halfpipe-fly
  vars:
    A: a
    B: b

