# yaml-language-server: $schema=../../.generated/schema.json
team: halfpipe-team
pipeline: pipeline-name

triggers:
- type: git
  branch: main
  ignored_paths:
  - README.md
  - '**.js'

tasks:
- type: run
  docker:
    image: ubuntu
  script: \echo hello
