team: CHANGE-ME
pipeline: halfpipe-e2e-concourse-init
feature_toggles:
- update-pipeline
triggers:
- type: git
  watched_paths:
  - e2e/concourse/init
tasks:
- type: run
  name: CHANGE-ME OPTIONAL NAME IN CONCOURSE UI
  script: ./gradlew CHANGE-ME
  docker:
    image: CHANGE-ME:tag
