# yaml-language-server: $schema=../../.generated/schema.json
team: halfpipe-team
pipeline: pipeline-name

feature_toggles:
- update-pipeline-and-tag

tasks:
- type: run
  name: test
  script: ../update-pipeline/a
  docker:
    image: node:9.5.0-alpine

- type: docker-compose
  name: A

- type: parallel
  tasks:
  - type: docker-compose
    name: B
  - type: docker-compose
    name: C
