# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
registries:
  ee-artifactory:
    type: maven-repository
    url: https://springernature.jfrog.io/artifactory/libs-release/
    username: ${{ secrets.EE_ARTIFACTORY_USERNAME }}
    password: ${{ secrets.EE_ARTIFACTORY_PASSWORD }}
updates:
- package-ecosystem: docker
  directories:
  - /**
  schedule:
    interval: weekly
  cooldown:
    default-days: 5
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - docker
- package-ecosystem: docker-compose
  directories:
  - /**
  schedule:
    interval: weekly
  cooldown:
    default-days: 5
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - docker-compose
- package-ecosystem: github-actions
  directories:
  - /
  schedule:
    interval: weekly
  cooldown:
    default-days: 5
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - github-actions
- package-ecosystem: gomod
  directories:
  - /**
  schedule:
    interval: weekly
  cooldown:
    default-days: 5
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - gomod
  groups:
    minor-and-patch:
      update-types:
      - minor
      - patch
- package-ecosystem: gradle
  directories:
  - /**
  schedule:
    interval: weekly
  cooldown:
    default-days: 5
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - gradle
  groups:
    minor-and-patch:
      update-types:
      - minor
      - patch
  registries:
  - ee-artifactory
