# yaml-language-server: $schema=../../.generated/schema.json
team: halfpipe-team
pipeline: pipeline-name

triggers:
- type: git
  branch: main
  watched_paths:
  - go.*
  - mise.toml

tasks:
- type: run
  name: build
  docker:
    image: foo
  script: \build
