package cmds

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/sirupsen/logrus"
	"github.com/spf13/afero"
	"github.com/spf13/cobra"
	"github.com/springernature/halfpipe/dependabot"
	"gopkg.in/yaml.v2"
)

func init() {
	var depth int
	var verbose bool
	var skipFolders []string
	var skipEcosystem []string

	logrus.SetFormatter(&logrus.TextFormatter{
		ForceColors:      true,
		DisableTimestamp: true,
	})
	logrus.SetOutput(os.Stderr)

	dependabotCmd := &cobra.Command{
		Use:   "dependabot",
		Short: "Creates a dependabot config",
		Run: func(cmd *cobra.Command, args []string) {
			if verbose {
				logrus.SetLevel(logrus.DebugLevel)
			}
			fs := afero.NewOsFs()
			pwd, err := os.Getwd()
			if err != nil {
				printErr(err)
				os.Exit(1)
			}

			c, err := dependabot.New(
				dependabot.NewWalker(afero.Afero{Fs: afero.NewBasePathFs(fs, pwd)}, depth, skipFolders),
				dependabot.NewFilter(skipEcosystem),
				dependabot.Render,
			).Resolve()
			if err != nil {
				printErr(err)
				os.Exit(1)
			}

			out, err := yaml.Marshal(c)
			if err != nil {
				printErr(err)
				os.Exit(1)
			}
			labelSet := map[string]bool{}
			for _, u := range c.Updates {
				for _, l := range u.Labels {
					labelSet[l] = true
				}
			}
			labels := make([]string, 0, len(labelSet))
			for l := range labelSet {
				labels = append(labels, l)
			}
			sort.Strings(labels)
			fmt.Println("# Generated by `halfpipe dependabot`")
			fmt.Println("# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json")
			fmt.Println("# Dependabot silently skips labels that don't exist in the repo. Create them with:")
			fmt.Printf("#   for label in %s; do gh label create \"$label\" --force; done\n", strings.Join(labels, " "))
			fmt.Println("#")
			fmt.Print(string(out))
		},
	}

	dependabotCmd.Flags().IntVar(&depth, "depth", 3, "Max depth to scan.")
	dependabotCmd.Flags().BoolVar(&verbose, "verbose", false, "Print verbose information")
	dependabotCmd.Flags().StringSliceVar(&skipFolders, "skip-folder", []string{}, "Skipped folders relative from root")
	dependabotCmd.Flags().StringSliceVar(&skipEcosystem, "skip-ecosystem", []string{}, "Skipped ecosystems. Find them at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem")

	rootCmd.AddCommand(dependabotCmd)
}
