# yaml-language-server: $schema=../../schema.json
team: engineering-enablement
pipeline: halfpipe-e2e-trigger-timer

triggers:
- type: timer
  cron: 5 4 * * 0-5

tasks:
- type: run
  name: hello
  docker:
    image: alpine
  script: \echo hello
