name: OCI Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ee-runner
    steps:
      - uses: actions/checkout@v7

      - uses: jdx/mise-action@v4

      - run: mise oci build
