name: Validate OpsLevel Configs
permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/opslevel.yml'
      - '**/opslevel.yaml'
      - '.github/workflows/validate-opslevel.yml'
  pull_request:
    paths:
      - '**/opslevel.yml'
      - '**/opslevel.yaml'
      - '.github/workflows/validate-opslevel.yml'

jobs:
  validate:
    runs-on: ee-runner
    steps:
      - uses: actions/checkout@v6
      - uses: springernature/ee-action-validate-opslevel@d6d996cf72bb6622e18fd03ad519d01f061d24fc # 1.0.5
        with:
          opslevel_api_token: ${{ secrets.OPSLEVEL_RW_TOKEN }}
